### ISSUE TITLE
Draw out all iOS pages

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#3]
## Task Details

> Formaly draw all pages / create mockup drawings for the iOS app and upload to invisionapp
##### Pages:
- [x] Login
- [x] News Feed
  - [x] Single News Item Page
- [x] Contacts
- [x] Profile Page
- [x] Single Course Page (Optional)

**Repo: [https://github.com/iRAMBI/iOS-mockups](https://github.com/iRAMBI/iOS-mockups)**

**Comment by ryansadio** [comment]
All pages specified except "Single Course Page" uploaded to organization repo. Please advice what Single Course page would look like. -R

### Edit:
- [ ] _Admin controls_ Add new article button in news page.
- [ ] Post new article page.
- Title
- Message
- Programid (CRN&stuff)
- Exp date
- Priority (Critical vs Normal)
- [x] Update _Detailed article page_, design is ugly.
- [x] Create _Detailed contacts page_.
- [x] Change _Bulletin_ to _News_
- [x] Selecting a single course from the _Profile page_ will open up an inner page with filtered news for that specific course.

### For further discussion:
- [ ] How will set-reps post news to specific sets if posting is determined by CRN number?
